// ============================================================
// Maintenance Standard Jobs — extracted from Flow 5
// Maps yacht names (as used in the Switch) to their job lists
// and the Yacht Schedule section GID for tracking
// ============================================================

const STANDARD_JOBS_DEFAULT = [
  "De-odorize holding tanks",
  "Clean AC filters and lint guards",
  "Check/Change water maker filters",
];

const STANDARD_JOBS_WITH_BATTERY = [
  "Check/Top up battery water",
  "De-odorize holding tanks",
  "Clean AC filters and lint guards",
  "Check/Change water maker filters",
];

// Per-yacht maintenance config
// project = maintenance project GID, charterSection = yacht schedule section GID
const YACHT_MAINTENANCE = {
  "Electrified":         { project: "930228245617935",  charterSection: "1201533939042402", jobs: STANDARD_JOBS_DEFAULT },
  "After Glow":          { project: "691587298515988",  charterSection: "1201533939042399", jobs: STANDARD_JOBS_DEFAULT },
  "Endless Summer":      { project: "717709282577739",  charterSection: "1201533939042403", jobs: STANDARD_JOBS_WITH_BATTERY },
  "Let It Go":           { project: "732995064675562",  charterSection: "1201533939042404", jobs: STANDARD_JOBS_WITH_BATTERY },
  "Osprey":              { project: "120612499680437",  charterSection: "1201533939042409", jobs: STANDARD_JOBS_WITH_BATTERY },
  "No Regrets":          { project: "123856243164731",  charterSection: "1201533939042410", jobs: STANDARD_JOBS_WITH_BATTERY },
  "Secret Oasis":        { project: "691495498921912",  charterSection: "1201533939042413", jobs: STANDARD_JOBS_DEFAULT },
  "Summer Breez":        { project: "1198206201710141", charterSection: "1201533939042414", jobs: STANDARD_JOBS_DEFAULT },
  "Home Sweet Home":     { project: "1199964646135475", charterSection: "1201533939042415", jobs: STANDARD_JOBS_DEFAULT },
  "Moonstruck":          { project: "887295831365148",  charterSection: "1201546378387133", jobs: STANDARD_JOBS_WITH_BATTERY },
  "Sol Liv":             { project: "1201060966855795", charterSection: "1201533939042416", jobs: STANDARD_JOBS_DEFAULT },
  "Sail La Vie":         { project: "1110518043677775", charterSection: "1201546378387134", jobs: STANDARD_JOBS_DEFAULT },
  "Home Again":          { project: "1201589713415165", charterSection: "1201589713415183", jobs: STANDARD_JOBS_DEFAULT },
  "Job Site":            { project: "1202117165700542", charterSection: "1202117165700546", jobs: STANDARD_JOBS_DEFAULT },
  "Windborne":           { project: "732995064675487",  charterSection: "1202205136050878", jobs: STANDARD_JOBS_WITH_BATTERY },
  "Auto Pirate":         { project: "1203226595626562", charterSection: "1203237266816984", jobs: STANDARD_JOBS_DEFAULT },
  "5 O'Clock Somewhere": { project: "1203866751839439", charterSection: "1203866751839442", jobs: STANDARD_JOBS_DEFAULT },
  "Home Away":           { project: "1205521963054572", charterSection: "1205521963054595", jobs: STANDARD_JOBS_DEFAULT },
  "Busy B's":            { project: "1205948903684939", charterSection: "1205952544276676", jobs: STANDARD_JOBS_DEFAULT },
  "Treasure Hunter":     { project: "1206122229775528", charterSection: "1206131284029027", jobs: STANDARD_JOBS_DEFAULT },
  "Sea Glass":           { project: "1207406595667894", charterSection: null, jobs: STANDARD_JOBS_DEFAULT },
  "Big Kid Island":      { project: "1207473667277308", charterSection: null, jobs: STANDARD_JOBS_DEFAULT },
  "The Drake":           { project: "1208391787698878", charterSection: null, jobs: STANDARD_JOBS_DEFAULT },
  "Southern Cross":      { project: "1210331621233575", charterSection: null, jobs: STANDARD_JOBS_DEFAULT },
  "Way Maker":           { project: "1210331621233578", charterSection: null, jobs: STANDARD_JOBS_DEFAULT },
  "Miles Away II":       { project: "1210775057987624", charterSection: null, jobs: STANDARD_JOBS_DEFAULT },
  "Decent Effort":       { project: "1211811642616860", charterSection: null, jobs: STANDARD_JOBS_DEFAULT },
};

// ============================================================
// Housekeeping Stage Hours — extracted from Flow 6
// ============================================================

const YACHT_STAGES = {
  "After Glow":          { A: 4, B: 2, C: 2 },
  "Let It Go":           { A: 4, B: 2, C: 2 },
  "Endless Summer":      { A: 4, B: 2, C: 2 },
  "Moonstruck":          { A: 4, B: 2, C: 2 },
  "No Regrets":          { A: 4, B: 2, C: 2 },
  "Osprey":              { A: 4, B: 2, C: 2 },
  "Secret Oasis":        { A: 5, B: 2.5, C: 2.5 },
  "Summer Breez":        { A: 8, B: 4, C: 4 },
  "Home Sweet Home":     { A: 8, B: 4, C: 4 },
  "Sol Liv":             { A: 8, B: 4, C: 4 },
  "Out Of Office":       { A: 8, B: 4, C: 4 },
  "Sail La Vie":         { A: 4, B: 2, C: 2 },
  "Home Again":          { A: 8, B: 4, C: 4 },
  "Job Site":            { A: 8, B: 4, C: 4 },
  "Windborne":           { A: 4, B: 2, C: 2 },
  "Auto Pirate":         { A: 8, B: 4, C: 4 },
  "5 O'Clock Somewhere": { A: 8, B: 4, C: 4 },
  "Home Away":           { A: 8, B: 4, C: 4 },
  "Busy B's":            { A: 8, B: 4, C: 4 },
  "Treasure Hunter":     { A: 8, B: 4, C: 4 },
  "Sea Glass":           { A: 8, B: 4, C: 4 },
  "Big Kid Island":      { A: 8, B: 4, C: 4 },
  "The Drake":           { A: 8, B: 4, C: 4 },
  "Southern Cross":      { A: 5, B: 2.5, C: 2.5 },
  "Way Maker":           { A: 5, B: 2.5, C: 2.5 },
  "Miles Away II":       { A: 8, B: 4, C: 4 },
  "Decent Effort":       { A: 8, B: 4, C: 4 },
};

// ============================================================
// Housekeeping Checklists — extracted from Flow 6
// ============================================================

const INTERIOR_A = [
  "Strip All Linen, remove all food and organize space",
  "Collect vessel laundry bags from Doris",
  "Strip all beds and collect all linen and food",
  "Stack pillows neatly in the cabins and salon",
  "Check Cupboards",
  "Inspect all cupboards in the cabins, galley, and salon to ensure they are clear",
  "Transport Linen",
  "Take all linen to the laundry for washing",
  "Brush Surfaces, Ledges, Under Beds and Sweep Debris",
  "Brush down all surfaces and ledges, especially areas with sand or crumbs, to the floor for the exterior cleaners to wash",
  "Lift up salon cushions, brush or wipe down and clean all areas underneath cushions to get rid of all dirt, sand, and hair",
  "Lift mattresses and sweep underneath the beds and around ledges, directing debris to the floor",
  "Sweep all debris down to the bottom of the stairwells",
  "Address Rust and Burnt Pots and Stove",
  "Spray rust remover on stainless steel surfaces with visible rust",
  "Spray oven cleaner inside the oven and on pots, allowing it to sit",
  "Check Inventory While Cleaning",
  "Wash and dry dishes, appliances, non-skid surfaces, and placemats from cupboards",
  "Pack dishes neatly away",
  "Ensure all appliances are working properly",
  "Check and clean all vessel ornaments - including outside baskets and plants",
  "Descale coffee machines using a cleaning solution",
  "Report Inventory Issues",
  "Notify Bev if any inventory items are missing, rusted, or need replacement",
  "Send a message with a detailed list and pictures",
  "Deep Clean Appliances",
  "Clean the oven, stove, and microwave thoroughly, ensuring no grease remains in the seams",
  "Storage Areas",
  "Clean inside ALL cupboards, drawers, and other storage areas - in galley, salon, and cabins",
  "Detail Other Areas",
  "Clean fans, light switches, radios, AC panels, vents, headboards, ledges, doors, and door rims",
  "Clean any marks on seating - fabric and leather",
  "Clean hard to reach places with an ear bud",
  "Polish Stainless and Surfaces",
  "Use a brush to clean interior stainless steel",
  "Wipe mirrors",
  "Clean and remove marks from all surfaces",
  "Organize the Charter Table",
  "Remove all items from the charter table",
  "Clean the table and pack items neatly",
  "Put back toilet brushes and holders, and cabin bins",
  "Leave the Vessel Neat and ORGANIZED",
  "Make sure ALL cushions are left inside - stacked on the salon seating in order of type and size",
  "Ensure nothing is laying around the vessel",
];

const INTERIOR_B = [
  "Collect Laundry",
  "Gather all linens from the laundry and take to the vessel",
  "Keep laundry bags stacked neatly",
  "Make All Beds Onboard",
  "Alert maintenance team that you are making beds on a specific vessel",
  "Use clean linens to make all beds on the yacht",
  "Stock Towels and Cover Cushions",
  "Place a full set of towels and beach towels onboard",
  "Carefully put all the clean covers on the interior and exterior cushions",
  "Make sure to keep them stacked neatly until put in place",
  "Add Extra Linens and Fill Soaps",
  "Pack additional linens and towels based on the number of guests",
  "Confirm the required quantity with Bev and Doris",
  "Ensure all shampoo, conditioner, shower gel, and hand soaps are filled to the top",
];

const INTERIOR_C = [
  "Collect Welcome Pack",
  "Retrieve the Welcome Pack and place all items onboard, in the correct place",
  "Shine ALL Surfaces",
  "Polish all walls and pipes in cupboards and compartments, checking thoroughly for mold",
  "Wipe down all leather and fabric seats onboard",
  "Shine all toilet brush holders and cabin bins",
  "Shine all light fixtures and light switches",
  "Polish all mirrors and windows until streak-free",
  "Use a Magic Eraser to shine steps and clean all white gel coat surfaces, including marks and doors",
  "Polish the top of the stove and the oven front",
  "Pick up and polish beneath decorative ornaments",
  "Shine all countertops and surfaces",
  "Perform Last Checks",
  "Inspect for mold in all areas, including cupboards, ice-makers, fridges, and freezers - CLEAN IF FOUND",
  "Recheck the chart table and wipe it if necessary",
  "Quick last inventory check - report to Bev if anything is missing",
  "Ensure there are no broken or rusty items anywhere, including pegs and ornaments",
  "Report any missing or broken items to Bev for replacement",
  "Final Cleaning",
  "Pour Fabuloso into toilets",
  "Sweep all floors and vacuum thoroughly",
  "Spray VOYAGE scent",
  "Mop with a clean mop",
];

const EXTERIOR_A = [
  "Remove Food and Trash",
  "Collect trash from the entire vessel",
  "Bring cabin bins to the cockpit for cleaning",
  "Remove all food, drinks, and trash from the vessel",
  "Fill Water Tanks",
  "Refill all water tanks to capacity",
  "Address Rust and Treat Grill",
  "Spray the grill with cleaner and let it sit",
  "Spray rust remover on stainless steel with visible rust, allowing it to sit",
  "Use a brush where necessary for stubborn areas",
  "Defrost and Treat Fridges, Freezers and Ice Makers",
  "Defrost and treat fridges, freezers, and ice makers with bleach",
  "Leave bleach to sit and sterilize",
  "Store Snorkel Gear",
  "Rinse snorkel gear and take it to storage",
  "Cockpit Lockers and Inventory",
  "Thoroughly clean the cooler",
  "Scrub the cockpit bin and cabin bins with bleach",
  "Empty, demould, clean, and organize all cockpit lockers",
  "Check and clean all inventory, ensuring both lockers and items are dry before repacking",
  "Report Inventory Issues",
  "Notify Bev if any inventory items are missing, rusted, or need replacement",
  "Send a message with a detailed list and pictures",
  "Clean BBQ",
  "Clean and wash the BBQ",
  "Pack away on older vessels / Add new sand for new vessels",
  "Thoroughly wash down bins and locker under sink and BBQ",
  "Rinse Vessel, Dinghy and Rust Remover",
  "Thoroughly hose down the vessel",
  "Wash off any rust remover residue",
  "Lift up all cushions on the vessel, brush them down and rinse areas underneath to get rid of all dirt, sand, and hair",
  "Hose down the cockpits and flybridge, including the ceiling under the grates",
  "Clean salt off drop down over the cockpit table and wash down cockpit table",
  "Thoroughly hose down the dinghy and clean and organize it in the dinghy locker",
  "Anchor and Deck Lockers",
  "Unpack, clean, and organize the anchor locker, ensuring no sand is left",
  "Unpack, clean, and organize other deck lockers, ensuring no sand is left",
  "Pack items away neatly and check or replace propane if applicable",
  "Wash Down Fridges, Salon, Galley and Stairwells",
  "Wash and vacuum all fridges, freezers, and ice makers from top to bottom",
  "Clean floor lockers and rims, floor boards, and floors, ensuring no sand, dirt, or hair is left",
  "Remove and clean anything in lockers before repacking dry",
  "Give anything that does not belong in the lockers to Bev",
  "Wash down stairwells and scrub stairs",
  "Do not drop bleach on the stairs; you will be responsible for detailing them",
  "Clean Heads, Toilet Brushes, Companionways, Cabin Floors and Walls",
  "Sanitize, demould, and wash all head compartments, toilet brushes, showers, sinks, drains, walls, and plastic curtains in crew cabins",
  "Report if new toilet brush heads are needed",
  "Wash down companionways, cabin walls, floor boards, and floors",
  "Sanitize, demould, and wash all pipes in all lockers and cupboards using bleach",
  "Wash in cabin seating lockers",
  "Sanitize, Clean and Dry Bilges",
  "Sanitize, demould, wash, and flush all pipes in bilges using bleach",
  "Ensure no hair is stuck in pipes",
  "Sanitize, demould, wash, and flush all bilges with bleach",
  "Reach deep into the bilge for thorough cleaning",
  "Remove all sand, hair, and dirt",
  "Vacuum out bilges and ensure no water is left standing",
  "Leave The Vessel Neat and ORGANIZED",
  "Final hose down of any footprints or dirt in the cockpit",
  "Ensure everything is left neat and organized",
  "Ensure nothing is laying around the vessel",
  "Put down wet mat provided by laundry",
  "Do not leave ugly towels laying on the boat or dock",
];

const EXTERIOR_B = [
  "Wash and Scrub Vessel Exterior and Hatches",
  "Wash and scrub the exterior of the vessel, including the hulls, down to the waterline",
  "Thoroughly clean all hatch recesses",
  "Inspect and Clean Compartments",
  "Check all exterior compartments and lockers for mold and unpleasant smells",
  "Empty and clean everything if any issues are detected",
  "Clean Exterior Cushions and Accessories",
  "Clean all exterior cushions, sail bags, and screens",
  "Ensure they are completely dry before fitting back or packing away",
  "Clean Dinghy and Life Rings",
  "Wash and scrub the dinghy and life rings, ensuring all marks are removed",
  "Check the dinghy locker - ensure all contents are clean, neat, and organized",
  "Empty and clean everything if any issues are detected",
  "Scrub Dive Platform, Teak Stairs and Sugar Scoops",
  "Scrub down the dive platform and clean between the slats, ensuring no hair is hanging down",
  "Scrub teak stairs so no marks are left behind",
  "Clean under the stairs",
  "Scrub the sugar scoops and treat any mold using bleach",
  "Clean and Dry Entire Cockpit",
  "Scrub the entire cockpit, including the ceiling, grating, under the grating, above the cockpit table, and the cockpit table itself",
  "Use a shammy cloth to dry and polish the cockpit and lockers",
  "Lay down a clean and wet mat as provided",
  "Ensure no ugly towels are left laying around",
];

const EXTERIOR_C = [
  "Polish Stainless Steel",
  "Shine all stainless steel surfaces to ensure they are spotless and streak-free",
  "Shine Windows",
  "Shine all windows for a clear, streak-free finish",
  "Polish Gelcoat, Instruments and Helm Station",
  "Shine the gelcoat to enhance its appearance and maintain its protective layer",
  "Polish and clean all instruments and the helm station",
  "Shine up Cockpit and Inventory",
  "Shine the cooler inside and outside and shine the cockpit bin",
  "Check interior and exterior lockers and bilges - ensure they are clean and dry",
  "Spray lockers and bilges with a cleaning solution",
  "Shine all surfaces in the cockpits and flybridge, including tables",
  "Shine cockpit floors and place a clean welcome mat",
];

const HOUSEKEEPING_LISTS = {
  INTERIOR_A,
  INTERIOR_B,
  INTERIOR_C,
  EXTERIOR_A,
  EXTERIOR_B,
  EXTERIOR_C,
};

module.exports = {
  YACHT_MAINTENANCE,
  YACHT_STAGES,
  HOUSEKEEPING_LISTS,
};
